services:
    midas:
        image: midas
        container_name: midas
        pull_policy: never
        build: .
        env_file:
            - .env

    midas_db:
        image: postgres:17.6-alpine3.22
        container_name: midas_postgres
        env_file:
            - .env
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: